CREATE DATABASE IF NOT EXISTS TEST_SNOWFLAKE_DATABASE;

USE DATABASE TEST_SNOWFLAKE_DATABASE;

CREATE SCHEMA IF NOT EXISTS TEST_SNOWFLAKE_SCHEMA;
CREATE SCHEMA IF NOT EXISTS TEST_SNOWFLAKE_ADDITIONAL;
CREATE SCHEMA IF NOT EXISTS TEST_SNOWFLAKE_PIPES;


ALTER TASK IF EXISTS TEST_TASK SUSPEND;
ALTER PIPE IF EXISTS TEST_SNOWFLAKE_PIPES.EVENT_PIPES SET PIPE_EXECUTION_PAUSED = TRUE;

INSERT OVERWRITE INTO TEST_SNOWFLAKE_DATABASE.TEST_SNOWFLAKE_SCHEMA.TEST_SNOWFLAKE_TABLE
SELECT DISTINCT * FROM TEST_SNOWFLAKE_DATABASE.TEST_SNOWFLAKE_SCHEMA.TEST_SNOWFLAKE_TABLE;

INSERT OVERWRITE INTO TEST_SNOWFLAKE_DATABASE.TEST_SNOWFLAKE_ADDITIONAL.JSON_TEST
SELECT DISTINCT * FROM TEST_SNOWFLAKE_DATABASE.TEST_SNOWFLAKE_ADDITIONAL.JSON_TEST;

ALTER TASK IF EXISTS TEST_TASK RESUME;
ALTER PIPE IF EXISTS TEST_SNOWFLAKE_PIPES.EVENT_PIPES SET PIPE_EXECUTION_PAUSED = FALSE;
